import type { Metadata } from "next";
import "./globals.scss";
import Navbar from "@/components/navbar";
import { notFound } from "next/navigation";
import { Providers } from "./providers";
import { loadMessages, routing } from "@/utils/intlUtils";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: {
    locale: "en" | "pl";
  };
};

const LocaleLayout: React.FC<Props> = async ({ children, params }) => {
  const { locale } = await params;

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await loadMessages(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body>
        <Providers locale={locale} messages={messages}>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default LocaleLayout;
